name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # build .net application and run unit tests
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

  # build application per Dockerfile and push image (artifact) to GHCR
  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/dotnet-api:latest
          docker build -t $IMAGE .
          docker push $IMAGE

  # deploy artifact to Droplet 
  # this is commented out because we want prod deploy to be manual
  #deploy:
  #  runs-on: ubuntu-latest
  #  needs: docker-build-push
  #  steps:
  #    - name: Deploy to Droplet
  #      uses: appleboy/ssh-action@v0.1.10
  #      with:
  #        host: ${{ secrets.DROPLET_IP }}
  #        username: ${{ secrets.DROPLET_USER }}
  #        key: ${{ secrets.DROPLET_SSH_KEY }}
  #        script: |
  #          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
  #          docker pull ghcr.io/${{ github.repository }}/dotnet-api:latest
  #          docker stop dotnet-api || true
  #          docker rm dotnet-api || true
  #          docker run -d --name dotnet-api -p 5000:80 ghcr.io/${{ github.repository }}/dotnet-api:latest
